### ISSUE TITLE
Observers modifying the state?

### ISSUE THREAD

**Issue by steffenfinsland** [mecid/redux-like-state-container-in-swiftui#10]
In this architecture, where would you place a piece of logic that is observing something and which needs to repeatedly update the state based on external factors?

For example a Reachability object that needs to update a connected state, or an AVPlayer which needs to repeatedly update a player state? How would they send actions through the reducer?

**Comment by mecid** [comment]
So, it is a side effect. You should wrap your long-living logic into a publisher and return it via reducer.

**Comment by steffenfinsland** [comment]
Okay thanks, then I understand. 😄 So then if you wanted to cancel one of those long-living publishers, how would you do it?

In your apps, has the ever-growing `effectCancellables` inside Store.swift been a concern? Do you do anything to clean that up at some point?

**Comment by mecid** [comment]
There is a production-ready implementation of store object that cleans the set of cancellables.
https://github.com/mecid/swiftui-recipes-app/blob/master/Recipes/Shared/Model/Store.swift

You should create a cancellable variable as a part of your state to control it from the reducer.
