### ISSUE TITLE
Integrating a Notification Center Publisher

### ISSUE THREAD

**Issue by mycroftcanner** [mecid/redux-like-state-container-in-swiftui#2]
First, I'd like to give you some praise. I read all your blog posts and you're amazing! 

How would integrate a Notification Center Publisher or a Location Manager with the Store state container?

**Comment by mecid** [comment]
Hi, i'm happy to hear that you like it. This is how you can use it with NotificationCenter publishers.

`struct AppState {
    var dayChangedNotification = false
}

enum AppAction: Action {
    case fetchLocation

    func mapToMutation() -> AnyPublisher<AppMutation, Never> {
        NotificationCenter.default.publisher(for: .NSCalendarDayChanged)
            .map { _ in AppMutation.set(dayChanged: true) }
            .eraseToAnyPublisher()
    }
}

enum AppMutation {
    case set(dayChanged: Bool)
}

let appReducer: Reducer<AppState, AppAction.Mutation> = { state, mutation in
    switch mutation {
    case let .set(dayChanged):
        state.dayChangedNotification = dayChanged
    }
}`

**Comment by mycroftcanner** [comment]
Thanks

**Comment by mycroftcanner** [comment]
Thanks again  @mecid.

I have one more question though as I am trying to wrap my head around this:

```swift
    func mapToMutation() -> AnyPublisher<AppMutation, Never> {
        NotificationCenter.default.publisher(for: .NSCalendarDayChanged)
            .map { _ in AppMutation.set(dayChanged: true) }
            .eraseToAnyPublisher()
    }
}
```

Isn't it a problem if every time  this action is called it is mapped again to the same Notification Center Publisher? 

Wouldn't the store end up subscribing to the same publisher multiple times and mutate the state as many times each time the notification is fired?

**Comment by mycroftcanner** [comment]
I understand this flow:

State -> View -> Action -> State -> View

Shouldn't there be a way to subscribe the store to long lived publishers that triggers a state mutation every time the publisher fires? 

Event -> State -> View

Please forgive me @ecid if I completely misunderstood this.

**Another question comes to mind:**

If an action doesn't depend on a publisher to mutate a value, should I just return a Just publisher to be mapped to the mutation like in the following example? Or am I overcomplicating things?

```swift
    case let .setPlaceholder(text):
      return Just(text)
        .map { SearchMutation.setPlaceholder($0) }
        .eraseToAnyPublisher()
```

**Comment by mecid** [comment]
@mycroftcanner nice questions. So let's start ;)

First of all it is normal to return Just with map to mutation, it is ok.

```
 func mapToMutation() -> AnyPublisher<AppMutation, Never> {
        NotificationCenter.default.publisher(for: .NSCalendarDayChanged)
            .map { _ in AppMutation.set(dayChanged: true) }
            .eraseToAnyPublisher()
    }
```

You can fire this action only once, and store will subscribe to changes there, you don't need send this action multiple times. It is enough to subscribe once and it will produce mutations as soon as event will fire.

**Comment by mycroftcanner** [comment]
Haha it makes sense now, thanks!!

What would be the simplest way to document and enforce that an action should be fired only once?

Thanks!

**Comment by mecid** [comment]
@mycroftcanner sorry, I didn't get last question.

**Comment by bonokite** [comment]
Hi, I don't know if the following question is related but I have doubts about how to handle multiple consecutive events, as when the user performs a search query and we use a debounce publisher to avoid performing too many requests. Any ideas?

**Comment by mecid** [comment]
@bonokite it is something which should be a part of your UI, store just run action when you send it. You can try to send it with delay ;)
