### ISSUE TITLE
Integrating a settings store

### ISSUE THREAD

**Issue by mycroftcanner** [mecid/redux-like-state-container-in-swiftui#3]
I've just read again your older posts, [Modeling app state using Store objects in SwiftUI](https://mecid.github.io/2019/09/04/modeling-app-state-using-store-objects-in-swiftui/) and [Building forms with SwiftUI](https://mecid.github.io/2019/06/19/building-forms-with-swiftui/) and I am wondering how would you refactor your Settings Store and integrate it into the state container as to avoid a secondary source of truth?

**Comment by mycroftcanner** [comment]
Can we just create a Settings child state container and decorate the variable with a `@UserDefault` property wrapper. 

Is this the right way or are we violating some pattern rule?

Do we still need to subscribe to `UserDefaults.didChangeNotification` since the state variable is marked `@Published` I guess an individual change made to the settings variable would fire an update?

**Comment by mecid** [comment]
@mycroftcanner the problem is that you can't declare your variable like this

```
@Published
@UserDefault(Constants.UserDefaults.sleepGoal, defaultValue: 8.0)
var sleepGoal: Double
```

It doesn't support multiple property wrappers. So we still need to subscribe on notification center.

**Comment by mycroftcanner** [comment]
@mecid You can manually compose property wrapper types (see [ref](https://github.com/apple/swift-evolution/blob/master/proposals/0258-property-wrappers.md#composition)).

```swift
@propertyWrapper
struct AB<Value> {
  private var storage: A<B<Value>>
  
  var wrappedValue: Value {
    get { storage.wrappedValue.wrappedValue }
    set { storage.wrappedValue.wrappedValue = newValue }
  }
}
```

**Comment by mycroftcanner** [comment]
Found this ([here](https://stackoverflow.com/a/57982560/12106051)).

```swift
private var cancellables = [String:AnyCancellable]()

extension Published {
    init(wrappedValue defaultValue: Value, key: String) {
        let value = UserDefaults.standard.object(forKey: key) as? Value ?? defaultValue
        self.init(initialValue: value)
        cancellables[key] = projectedValue.sink { val in
            UserDefaults.standard.set(val, forKey: key)
        }
    }
}

class Settings: ObservableObject {
    @Published(key: "isLogedIn") var isLogedIn = false
    ...
}
```

**Comment by mecid** [comment]
I'm not sure you we really need it. You ca

**Comment by mecid** [comment]
I'm not sure you we really need it. You can send action on app launch which use publisher on user defaults change notification. This is how I do it right now ;)
