### ISSUE TITLE
Why do you use global variables?

### ISSUE THREAD

**Issue by mycroftcanner** [mecid/redux-like-state-container-in-swiftui#6]
I am just wondering why do you need to use global variables. For dependencies you could use Michael Long's [approach](https://github.com/hmlongco/Resolver) with [@Injected property wrappers](https://medium.com/better-programming/taking-swift-dependency-injection-to-the-next-level-b71114c6a9c6).

The new version of your store with the binding to action extension is amazing btw! 
Great work!

**Comment by mycroftcanner** [comment]
never mind I just watch that How to Control the World talk... makes sense...

However in the other repo ... what not use Current.store?

**Comment by mecid** [comment]
@mycroftcanner Hi, I updated the file to add the link for the talk about this DI method.

I use World only for side effects like URL session, analytics, etc.
