### ISSUE TITLE
Question: Why is the state passed by reference to the reducer

### ISSUE THREAD

**Issue by skinandbones** [mecid/redux-like-state-container-in-swiftui#7]
Thanks for sharing all of this great information.  It's been very helpful 👍 

In my flux past, I've normally treated state as immutable and the reducer returns a new state.  For example,
```swift
typealias Reducer<State, Action> = (State, Action) -> State
```

However, you've chosen to pass state by reference like this:
```swift
typealias Reducer<State, Action> = (inout State, Action) -> Void
```
Given you've applied this architecture to a couple apps and have some experience with it, I'm wondering if you can share any of the reasoning why you preferred pass by reference.  Thanks!

**Comment by mecid** [comment]
Hi @skinandbones,
It is just syntactic sugar, State is a value type and can't be passed as a reference.

**Comment by skinandbones** [comment]
Got it!   `inout` is really a copy-in-copy-out.   That makes a lot more sense.  Thanks for the clarification.
