### ISSUE TITLE
Question: What are the performance implications of having one store and what are the alternatives?

### ISSUE THREAD

**Issue by garsdle** [mecid/redux-like-state-container-in-swiftui#8]
@mecid First of all I freaking love your blog and all the helpful content you create, so thanks for all of that! I only wish you had an RSS feed so I could get notified on each post.

I recently switched my own app to using a single store that's in an ObservableObject class (much like you do in this repo) but I've had to do all sorts tricks to make sure data changes to different parts of my store don't cause updates in unrelated views.

For a bit I thought this was the right answer: https://nalexn.github.io/swiftui-observableobject/
Eventually I ended up making my own manual ObservableObject wrapper that can wrap my store and filter but it's a bit messy. Now I am wondering if I should just have many ObservableObjects or even go back to MVVM.

Given your amazing swiftUI insights I was wondering what your take on these architecture questions are.

**Comment by mecid** [comment]
Hi @garsdle,

**Comment by mecid** [comment]
Hi @garsdle,
Thanks for your feedback, here is the RSS feed url http://swiftwithmajid.com/feed.xml

SwiftUI diffing is super fast and should not update the views that didn't change.

**Comment by mecid** [comment]
Also you can check the source code of the Store class. It has a projection method that can play the role of ViewModel to format your data.

**Comment by mecid** [comment]
@garsdle Also you can check the source code of the Store class. It has a projection method that can play the role of ViewModel to format your data.
https://github.com/SwiftRex/SwiftRex/blob/develop/Sources/SwiftRex/CoreTypes/Store/StoreType%2BProjection.swift

**Comment by garsdle** [comment]
Awesome stuff, thanks for the quick reply. I subbed to the feed! 

Just to make sure I understand, are you saying that [your container view](https://github.com/mecid/redux-like-state-container-in-swiftui/blob/87c2077dadc9ebffe2633b4d0466bb63a1e84ea3/GithubSearch/SearchView.swift#L26-L41) will update from any store update but it won't matter because swiftUI is fast enough to handle it? In effect you are kind of using the view itself as a filter for your store updates?

**Comment by mecid** [comment]
@garsdle even without container views, it should work very fast, but yes it plays the role of a filter. Container views allow you to reuse your views and make them Equatable to provide custom diffing.

**Comment by golangnext** [comment]
@mecid  i don't think so
`SwiftUI diffing is super fast and should not update the views that didn't change.`

Here is the exampe: when we click the button, `mainView` is always re-rendered,  which is a potential performance impact.

```swift
struct MainView: View {
    @ObservedObject var store = AppStore()

    var body: some View {
        print("mainView")
        return Form {
            SubView(date: $store.date)
            Button("Press it") {
                self.store.date = Date().description
            }
        }
    }
}

struct SubView: View {
    @Binding var date: String
    var body: some View {
        print("subView")
        return Text(date)
    }
}

class AppStore:ObservableObject{
    @Published var date:String = Date().description
}

**Comment by mecid** [comment]
SwiftUI runs the body property to calculate the changes. It doesn’t mean it renders stuff every time. The body property returns the representation of the view and SwiftUI uses it to diff it with previous hierarchy. If something changes it renders changes.

**Comment by garsdle** [comment]
@mecid I'm wondering if you still feel this way about body calculation? I remember we interacted a little at WWDC and you mention the idea of something akin to MVVM with passthrough.

**Comment by mecid** [comment]
@garsdle I'm still using this approach and it looks like a best way to build apps using SwiftUI at the moment.

**Comment by garsdle** [comment]
Thanks for the update!
